import 'package:hive/hive.dart';

part 'favorite_item.g.dart'; // This file is generated by Hive

@HiveType(typeId: 0)
class FavoriteItem extends HiveObject {
  @HiveField(0)
  final String title;

  @HiveField(1)
  final String imagePath;

  FavoriteItem({
    required this.title,
    required this.imagePath,
  });
}
